version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.3

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            gateway/.* run-build-gateway-job true
            service/.* run-build-service-job true
          base-revision: development
          config-path: .circleci/continue_config.yml