version: 2.1

parameters:
  run-build-gateway-job:
    type: boolean
    default: false
  run-build-service-job:
    type: boolean
    default: false

executors:
  go:
    working_directory: ~/app
    docker:
      - image: cimg/go:1.17
    resource_class: small

jobs:
  build-gateway:
    executor: go
    steps:
      - run: go version
      - run: ls -la

  build-service:
    executor: go
    steps:
      - run: go version
      - run: ls -la

workflows:
  gateway:
    when: << pipeline.parameters.run-build-gateway-job >>
    jobs:
      - build-gateway

  service:
    when: << pipeline.parameters.run-build-service-job >>
    jobs:
      - build-service